name: 'GH Node Action'
description: 'Braindead example'
author: 'Noah Ispas'
inputs:
  api_token:
    required: false
    description: 'Some API token'
outputs:
  output_var:
    description: 'Some output variable'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api_token}}